name: commonapp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/alucard.jpg
    - assets/girl.jpeg
    - assets/images/ic_main_tab_company_nor.png
    - assets/images/ic_main_tab_company_pre.png
    - assets/images/ic_main_tab_contacts_nor.png
    - assets/images/ic_main_tab_contacts_pre.png
    - assets/images/ic_main_tab_find_nor.png
    - assets/images/ic_main_tab_find_pre.png
    - assets/images/ic_main_tab_my_nor.png
    - assets/images/ic_main_tab_my_pre.png
    - assets/images/pic_bg.jpg

  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf